source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'haml'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'rspec-rails'
gem 'hashie'
gem 'pg_search'
gem 'aws-sdk', '~> 1.0'
gem 'elasticsearch'
gem 'dotenv'
gem 'omniauth-google-oauth2'
gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'faker' # will need to be removed later, used for creating fake data

# Use unicorn as the app server
gem 'unicorn'

group :development do
  gem 'thin'
  gem 'fog'
  gem 'awesome_print'
end

group :test do
  gem 'timecop'
end
